#!/bin/bash

THEME=$1
THEME_DIR="$HOME/arch-i3wm-x11/themes"
CONFIG_DIR="$HOME/.config"

if [ -z "$THEME" ]; then
    echo "Usage: $0 [ocean|black]"
    exit 1
fi

if [ ! -d "$THEME_DIR/$THEME" ]; then
    echo "Error: Theme '$THEME' not found."
    exit 1
fi

echo "Switching to theme: $THEME"

xrdb -merge "$THEME_DIR/$THEME/Xresources"

BG=$(xrdb -query | grep "*background:" | awk '{print $2}')
FG=$(xrdb -query | grep "*foreground:" | awk '{print $2}')
ACCENT=$(xrdb -query | grep "*accent:" | awk '{print $2}')
URGENT=$(xrdb -query | grep "*color1:" | awk '{print $2}')
ALPHA=$(xrdb -query | grep "*.alpha:" | awk '{print $2}')

if [ -z "$ALPHA" ]; then ALPHA="0.90"; fi

cat > "$CONFIG_DIR/kitty/current-theme.conf" <<EOF
# Generated by switch.sh
foreground ${FG}
background ${BG}
background_opacity ${ALPHA}
selection_foreground ${BG}
selection_background ${ACCENT}
url_color ${ACCENT}
cursor ${FG}
active_border_color ${ACCENT}
inactive_border_color ${BG}
EOF

killall -SIGUSR1 kitty 2>/dev/null

cat > "$CONFIG_DIR/rofi/theme.rasi" <<EOF
* {
    bg: ${BG}E6;
    bg-alt: ${BG};
    fg: ${FG};
    accent: ${ACCENT};
    urgent: ${URGENT};
    background-color: @bg;
    text-color: @fg;
}
EOF

"$HOME/scripts/utils/set-wallpaper.sh"

"$CONFIG_DIR/polybar/launch.sh" &
i3-msg reload >/dev/null

echo "Done."