#!/bin/bash

THEME=$1
REPO_DIR="$HOME/arch-i3wm-x11"
SCRIPT_DIR="$HOME/scripts"

if [ -z "$THEME" ]; then
    echo "Usage: $0 [ocean|black]"
    exit 1
fi

if [ ! -d "$REPO_DIR/themes/$THEME" ]; then
    echo "Error: Theme '$THEME' not found."
    exit 1
fi

echo "Switching to $THEME theme..."

# Update Xresources
cp "$REPO_DIR/themes/$THEME/Xresources" "$HOME/.Xresources"
xrdb -merge "$HOME/.Xresources"
echo "$THEME" > "$HOME/.config/current_theme"

# Generate Rofi Theme
BG=$(xrdb -query | grep -i "background:" | head -n1 | awk '{print $2}')
FG=$(xrdb -query | grep -i "foreground:" | head -n1 | awk '{print $2}')
ACC=$(xrdb -query | grep -i "accent:" | head -n1 | awk '{print $2}')

cat > "$HOME/.config/rofi/theme.rasi" <<EOF
* {
    bg: ${BG}E6;
    bg-alt: ${BG};
    fg: ${FG};
    accent: ${ACC};
    background-color: @bg;
    text-color: @fg;
}
EOF

# 3. GENERATE KITTY THEME (Dynamic from Xresources)
cat > "$HOME/.config/kitty/current-theme.conf" <<EOF
# Generated by switch.sh
foreground ${FG}
background ${BG}
selection_foreground ${BG}
selection_background ${FG}
url_color ${ACC}

color0  $(xrdb -query | grep -i "color0:" | head -n1 | awk '{print $2}')
color1  $(xrdb -query | grep -i "color1:" | head -n1 | awk '{print $2}')
color2  $(xrdb -query | grep -i "color2:" | head -n1 | awk '{print $2}')
color3  $(xrdb -query | grep -i "color3:" | head -n1 | awk '{print $2}')
color4  $(xrdb -query | grep -i "color4:" | head -n1 | awk '{print $2}')
color5  $(xrdb -query | grep -i "color5:" | head -n1 | awk '{print $2}')
color6  $(xrdb -query | grep -i "color6:" | head -n1 | awk '{print $2}')
color7  $(xrdb -query | grep -i "color7:" | head -n1 | awk '{print $2}')
color8  $(xrdb -query | grep -i "color8:" | head -n1 | awk '{print $2}')
color9  $(xrdb -query | grep -i "color9:" | head -n1 | awk '{print $2}')
color10 $(xrdb -query | grep -i "color10:" | head -n1 | awk '{print $2}')
color11 $(xrdb -query | grep -i "color11:" | head -n1 | awk '{print $2}')
color12 $(xrdb -query | grep -i "color12:" | head -n1 | awk '{print $2}')
color13 $(xrdb -query | grep -i "color13:" | head -n1 | awk '{print $2}')
color14 $(xrdb -query | grep -i "color14:" | head -n1 | awk '{print $2}')
color15 $(xrdb -query | grep -i "color15:" | head -n1 | awk '{print $2}')
EOF

kill -SIGUSR1 $(pidof kitty) 2>/dev/null || true

if [ -x "$SCRIPT_DIR/utils/set-wallpaper.sh" ]; then
    "$SCRIPT_DIR/utils/set-wallpaper.sh"
fi

i3-msg reload > /dev/null
"$HOME/.config/polybar/launch.sh" &

if command -v dunstify &> /dev/null; then
    dunstify "Theme System" "Applied theme: $THEME" -u low -r 9991
fi

echo "-> Done."